### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Shalyapin-Polytech/Journal#1]
1. `testRemove ` ничего не проверяет
2. Уберите конкретные классы коллекций из типов возвращаемых значений и замените на интерфейсы. В типах локальных переменных тоже лучше заменить.

**Comment by Shalyapin-Polytech** [comment]
1. `testRemove` проверяет, бросается ли исключение при просмотре удаленной записи.
2. Убрал.

**Comment by Shalyapin-Polytech** [comment]
Ну да, и у меня на компьютере тест проходит.
![default](https://user-images.githubusercontent.com/31887973/37839605-e83efe82-2ecb-11e8-82f3-9dfafaba8f71.jpg)

**Comment by gagarski** [comment]
Да, справедливо, я не туда смотрел.
